### ISSUE TITLE
Year 2036 Considerations

### ISSUE THREAD

**Issue by alvestrand** [alvestrand/id-abs-capture-timestamp#3]
Raised by Jonathan Lennox:

Draft should describe how to deal with the NTP timestamp overflow in 2036.
"Interpret as closest time to current time" is probably Good Enough.

**Comment by JonathanLennox** [comment]
RFC 5905 [NTPv4] Section 4 gives the formulas this, computing the "era" from the current time, and then evaluating an NTP timestamp in the context of the era.
