### ISSUE TITLE
Describe how the capture time offset is consumed

### ISSUE THREAD

**Issue by JonathanLennox** [alvestrand/id-abs-capture-timestamp#5]
There's a lot of confusion about the capture time offset field, so it'd be useful to describe (at a high level) some examples of code that uses it, and explains why the plain capture time isn't sufficient.

**Comment by Arctunix** [comment]
Perhaps an explicit mention of that it's main purpose is to facilitate the calculation of one-way delay? Other functionality (e.g. lip sync across multiple capture systems) would then derive from that.
